.PHONY: all test testlocal

all: test

test:
	go test -race -cover ./...

BITCOIN_CLI_PATH := "../bitcoin-cli" $(BITCOIN_CLI_PATH)
BITCOIN_NETWORK := 3 $(BITCOIN_NETWORK) # 3: Testnet3, 255: Mainnet
BITCOIND_ADDR := "" $(BITCOIND_ADDR)
BITCOIND_PORT := "" $(BITCOIND_PORT)
BITCOIND_RPC_USER := "" $(BITCOIND_RPC_USER)
BITCOIND_RPC_PASSWORD := "" $(BITCOIND_RPC_PASSWORD)
test-local:
	BITCOIN_CLI_PATH=$(BITCOIN_CLI_PATH) \
	BITCOIN_NETWORK=$(BITCOIN_NETWORK) \
	BITCOIND_ADDR=$(BITCOIND_ADDR) BITCOIND_PORT=$(BITCOIND_PORT) \
	BITCOIND_RPC_USER=$(BITCOIND_RPC_USER) BITCOIND_RPC_PASSWORD=$(BITCOIND_RPC_PASSWORD) \
	go test -count=1 -race -cover -tags localTest ./...
