openapi: 3.0.0
info:
  version: "0.1.0"
  title: "BBc-1 BTC Gateway"
  description: ""
  termsOfService: ""
  contact:
    name: "github.com/ebiiim/btcgw"
    url: "https://github.com/ebiiim/btcgw"
  license:
    name: "Apache-2.0"
    url: "https://github.com/ebiiim/btcgw/blob/main/LICENSE"
servers:
  - url: ""
tags:
  - name: Anchor
    description: ""
  - name: API Key
    description: ""
paths:
  /anchors/domains/{domain}/digests/{digest}:
    get:
      tags:
        - "Anchor"
      summary: Gets the anchor specified by BBc-1 domain ID and BBc-1 digest.
      responses:
        "200":
          description: Gets the anchor successfully and returns the AnchorRecord.
          content:
            applycation/json:
              schema:
                $ref: "#/components/schemas/AnchorRecord"
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/ErrAnchorNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - "Anchor"
      summary: Registers an anchor with specified BBc-1 domain ID and BBc-1 digest.
      security:
        - ApiKey: []
      responses:
        "200":
          description: Registration completes successfully and returns the AnchorRecord.
          content:
            applycation/json:
              schema:
                $ref: "#/components/schemas/AnchorRecord"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Unauthorized.
        "500":
          $ref: "#/components/responses/InternalServerError"
    patch:
      tags:
        - "Anchor"
      summary: Requests to update the status of the anchor specified by BBc-1 domain ID and BBc-1 digest.
      responses:
        "204":
          description: Successful.
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/ErrAnchorNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
    parameters:
      - name: domain
        in: path
        description: BBc-1 domain ID in hexadecimal string
        required: true
        schema:
          type: string
          example: 456789abc0ef0123456089abcdef0023456789a0cdef0123406789abcde00123
      - name: digest
        in: path
        description: BBc-1 digest in hexadecimal string
        required: true
        schema:
          type: string
          example: 56789abcd0f0123456709abcdef0103456789ab0def0123450789abcdef01234
  /apikeys/create:
    post:
      tags:
        - API Key
      summary: Creates an API Key associated with the BBc-1 domain specified by ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BBc1Domain"
      responses:
        "200":
          description: Creation completes successfully and returns the APIKey.
          content:
            applycation/json:
              schema:
                $ref: "#/components/schemas/APIKey"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /apikeys/delete:
    post:
      tags:
        - API Key
      summary: Deletes the specified API Key.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/APIKey"
      responses:
        "204":
          description: Successful or not found.
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    BadRequest:
      description: Invalid request received, returns an Error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: API key is missing or invalid.
      headers:
        WWW_Authenticate:
          schema:
            type: string
    InternalServerError:
      description: Internal error occurred, returns an Error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            error: "btcgw::unexpected_error"
            error_description: "An unexpected error has occurred, please contact us."
    ErrAnchorNotFound:
      description: Anchor not found, returns an Error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Anchor:
      type: object
      required:
        - version
        - chain
        - time
        - domain
        - digest
      properties:
        version:
          type: integer
          example: 1
          description: Anchor version. `1` `255`(test use only)
        chain:
          type: string
          example: Mainnet
          description: Target Bitcoin network. `Mainnet` `Testnet3` `Testnet4`(unsupported)
        time:
          type: integer
          example: 1612449628
          description: Timestamp embedded in the Anchor.
        domain:
          type: string
          example: 456789abc0ef0123456089abcdef0023456789a0cdef0123406789abcde00123
          description: BBc-1 domain ID in hexadecimal string.
        digest:
          type: string
          example: 56789abcd0f0123456709abcdef0103456789ab0def0123450789abcdef01234
          description: BBc-1 digest in hexadecimal string.
    AnchorRecord:
      type: object
      required:
        - anchor
        - btctx
        - time
        - confirmations
      properties:
        anchor:
          $ref: "#/components/schemas/Anchor"
        btctx:
          type: string
          example: 6928e1c6478d1f55ed1a5d86e1ab24669a14f777b879bbb25c746543810bf916
          description: Bitcoin transaction ID in hexadecimal string.
        time:
          type: integer
          example: 1612449916
          description: Timestamp in Bitcoin block chain.
        confirmations:
          type: integer
          example: 823
          description: Comfirmations of the Bitcoin transaction.
        bbc1name:
          type: string
          example: hoge_org
          description: BBc-1 domain name that is not embedded in the Bitcoin transaction.
        note:
          type: string
          example: hello world
          description: Arbitrary string that is not embedded in the Bitcoin transaction.
    BBc1Domain:
      type: object
      required:
        - domain
      properties:
        domain:
          type: string
          example: 456789abc0ef0123456089abcdef0023456789a0cdef0123406789abcde00123
          description: BBc-1 domain ID in hexadecimal string.
    APIKey:
      type: object
      required:
        - key
      properties:
        key:
          type: string
          example: "8899aabbccddeeff0011223344556677"
          description: API key (must be kept secret).
    Error:
      type: object
      required:
        - error
        - code
      properties:
        error:
          type: string
          example: btcgw::tx_not_found
          description: Error code with prefix `btcgw::`.
        error_description:
          type: string
          example: Transaction not found.
          description: Message to the user.
