name: test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.15"
          - "1.16"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: prepare .env
        run: cp .env.sample .env
      - name: generate and build
        run: make build
      - name: set timezone for test
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"
      - name: test
        run: go test -v -race -coverprofile cover.out ./...
      - name: send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
          flag-name: go${{ matrix.go }}
          parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
